// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcvvtzdvkfkeeiiggrxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdnZ0emR2a2ZrZWVpaWdncnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNjEyMTMsImV4cCI6MjA3NzgzNzIxM30.KpaW0WA6i7Yj-nOp4C0t0tGuQbBvI3nBDbc60PiQY9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});